using MongoDB.Bson.Serialization.Attributes;

namespace HotBag.EntityBase
{
    public interface IMongoEntityBase<TPrimaryKey> : IEntityBase<TPrimaryKey>
    {
        //
        // Summary:
        //     Unique identifier for this entity.
        //     standard BSonId generated by MongoDb 
        [BsonId]
        TPrimaryKey Id { get; set; }
    } 
}
