namespace HotBag.EntityBase
{
    public interface IMongoEntityBase<TPrimaryKey>
    {
        //
        // Summary:
        //     Unique identifier for this entity.
        //     standard BSonId generated by MongoDb 
        TPrimaryKey Id { get; set; }
    } 
}
