using HotBag.EntityBase;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Driver;

namespace HotBag.MongoDb.Context
{
    public interface IMongoDbContext
    {
        IMongoCollection<ApplicationSettings> ApplicationSettings { get; }
        //IMongoCollection<EditionFeatureSetting> EditionFeatureSettings { get; }

    }

    public class ApplicationSettings : IMongoEntityBase<ObjectId>
    {
        public string ApplicationName { get; set; }

        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId Id { get; set; }
    }
}
